# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-15 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatportal', '0003_auto_20170115_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senateseat',
            name='sclass',
            field=models.IntegerField(choices=[(1, 'Class I'), (2, 'Class II'), (3, 'Class III')], verbose_name='class of Seat'),
        ),
    ]
