# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-15 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatportal', '0004_auto_20170115_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='senateseat',
            options={'verbose_name_plural': 'Seats'},
        ),
        migrations.AlterModelOptions(
            name='statedemographics',
            options={'verbose_name_plural': 'State Demographics'},
        ),
        migrations.AlterField(
            model_name='senateseat',
            name='vacant',
            field=models.BooleanField(default=0, verbose_name='Is the Seat Vacant?'),
        ),
    ]
