# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-15 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seatportal', '0005_auto_20170115_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='senateseat',
            name='demo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seatportal.StateDemographics'),
            preserve_default=False,
        ),
    ]
