# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-15 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seatportal', '0006_senateseat_demo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senateseat',
            name='demo_id',
        ),
    ]
