# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatportal', '0008_auto_20170115_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='senateseat',
            name='region',
            field=models.CharField(choices=[('MW', 'Midwest'), ('NE', 'Northeast'), ('S', 'The South'), ('W', 'The West')], default='USA', max_length=3, verbose_name='region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='senateseat',
            name='swingseat',
            field=models.BooleanField(default=False, verbose_name='is Seat up for Individual Election?'),
        ),
    ]
