# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-21 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_dem', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='democrat Polling Average')),
                ('avg_gop', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='republican Polling Average')),
                ('avg_ind', models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='independent Polling Average (Can be NULL)')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sclass', models.IntegerField(choices=[(1, 'Class I'), (2, 'Class II'), (3, 'Class III')])),
                ('state', models.CharField(choices=[(b'AL', 'Alabama'), (b'AK', 'Alaska'), (b'AS', 'American Samoa'), (b'AZ', 'Arizona'), (b'AR', 'Arkansas'), (b'AA', 'Armed Forces Americas'), (b'AE', 'Armed Forces Europe'), (b'AP', 'Armed Forces Pacific'), (b'CA', 'California'), (b'CO', 'Colorado'), (b'CT', 'Connecticut'), (b'DE', 'Delaware'), (b'DC', 'District of Columbia'), (b'FL', 'Florida'), (b'GA', 'Georgia'), (b'GU', 'Guam'), (b'HI', 'Hawaii'), (b'ID', 'Idaho'), (b'IL', 'Illinois'), (b'IN', 'Indiana'), (b'IA', 'Iowa'), (b'KS', 'Kansas'), (b'KY', 'Kentucky'), (b'LA', 'Louisiana'), (b'ME', 'Maine'), (b'MD', 'Maryland'), (b'MA', 'Massachusetts'), (b'MI', 'Michigan'), (b'MN', 'Minnesota'), (b'MS', 'Mississippi'), (b'MO', 'Missouri'), (b'MT', 'Montana'), (b'NE', 'Nebraska'), (b'NV', 'Nevada'), (b'NH', 'New Hampshire'), (b'NJ', 'New Jersey'), (b'NM', 'New Mexico'), (b'NY', 'New York'), (b'NC', 'North Carolina'), (b'ND', 'North Dakota'), (b'MP', 'Northern Mariana Islands'), (b'OH', 'Ohio'), (b'OK', 'Oklahoma'), (b'OR', 'Oregon'), (b'PA', 'Pennsylvania'), (b'PR', 'Puerto Rico'), (b'RI', 'Rhode Island'), (b'SC', 'South Carolina'), (b'SD', 'South Dakota'), (b'TN', 'Tennessee'), (b'TX', 'Texas'), (b'UT', 'Utah'), (b'VT', 'Vermont'), (b'VI', 'Virgin Islands'), (b'VA', 'Virginia'), (b'WA', 'Washington'), (b'WV', 'West Virginia'), (b'WI', 'Wisconsin'), (b'WY', 'Wyoming')], max_length=2)),
                ('party', models.CharField(choices=[('R', 'Republican'), ('D', 'Democratic'), ('C-IND', 'Independent (CON)'), ('P-IND', 'Independent (PROG)')], max_length=25)),
                ('holder', models.CharField(max_length=25, verbose_name='username of Present Holder')),
                ('character', models.CharField(max_length=55, verbose_name='character Name of Present Holder')),
                ('demographic_p', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='progressive Demographic')),
                ('demographic_m', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='moderate Demographic')),
                ('demographic_c', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='conservative Demographic')),
                ('seat_id', models.CharField(default='NFound', max_length=6, unique=True, verbose_name='idenficiation of Seat')),
            ],
        ),
        migrations.AddField(
            model_name='pollingdata',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling.Seat', to_field='seat_id'),
        ),
    ]
