# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seatportal', '0008_auto_20170115_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_dem', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='democrat Polling Average')),
                ('avg_gop', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='republican Polling Average')),
                ('avg_ind', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='independent Polling Average (Can be NULL)')),
                ('series', models.IntegerField(default=0, verbose_name='polling Series Number')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seatportal.SenateSeat')),
            ],
        ),
    ]
