# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-28 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='news for Front Page Display')),
                ('date', models.DateField(auto_now=True, verbose_name='date of Publication')),
            ],
        ),
        migrations.CreateModel(
            name='WinningChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance_gop', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='GOP Chance of Winning')),
                ('chance_dnc', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='DNC Chance of Winning')),
                ('chance_ind', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='IND Chance of Winning (Can be NULL')),
            ],
        ),
        migrations.AlterModelOptions(
            name='pollingdata',
            options={'verbose_name_plural': 'Polling Data'},
        ),
        migrations.AlterField(
            model_name='pollingdata',
            name='series',
            field=models.IntegerField(default=0, verbose_name='polling Series Number (Round of polling e.g. First series is 1)'),
        ),
        migrations.AddField(
            model_name='winningchanges',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling.PollingData'),
        ),
    ]
