# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_auto_20161221_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_id',
            field=models.CharField(default='', max_length=6, null=True, unique=True, verbose_name='idenficiation of Seat'),
        ),
    ]
