# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-28 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_auto_20170128_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winningchanges',
            options={'verbose_name_plural': 'Chances of Winning'},
        ),
        migrations.AlterField(
            model_name='winningchanges',
            name='chance_ind',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='IND Chance of Winning (Can be NULL'),
        ),
    ]
