# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-29 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0003_auto_20170128_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallChances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance_gop', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Overall GOP Chance of Winning')),
                ('chance_dnc', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Overall DNC Chance of Winning')),
            ],
            options={
                'verbose_name_plural': 'Chances of Winning Senate Majority',
            },
        ),
        migrations.AlterField(
            model_name='winningchanges',
            name='chance_ind',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='IND Chance of Winning'),
        ),
    ]
