# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-29 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0004_auto_20170129_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollingdata',
            options={'get_latest_by': 'series', 'verbose_name_plural': 'Polling Data'},
        ),
        migrations.AddField(
            model_name='contentnews',
            name='topbar',
            field=djrichtextfield.models.RichTextField(default='A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollingdata',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date of Polling'),
        ),
        migrations.AddField(
            model_name='pollingdata',
            name='incumbent',
            field=models.CharField(max_length=40, null=True, verbose_name='Surname of Incumbent'),
        ),
    ]
